-- DASH DIÁRIO — classificação setorial inicial da base de 100 empresas
-- Observação: classificação ampla e educacional para melhorar a leitura do site.

UPDATE empresas_fundamentalistas
SET setor = CASE ticker
    WHEN 'HYPE3' THEN 'Saúde e farmacêutica'
    WHEN 'RECV3' THEN 'Petróleo, gás e combustíveis'
    WHEN 'ISAE4' THEN 'Energia elétrica'
    WHEN 'SAPR11' THEN 'Saneamento'
    WHEN 'IGTI11' THEN 'Shopping centers'
    WHEN 'ALUP11' THEN 'Energia elétrica'
    WHEN 'SMTO3' THEN 'Açúcar, etanol e bioenergia'
    WHEN 'VIVT3' THEN 'Telecomunicações'
    WHEN 'LREN3' THEN 'Varejo'
    WHEN 'AZZA3' THEN 'Vestuário, calçados e consumo'
    WHEN 'BRSR6' THEN 'Bancos'
    WHEN 'FLRY3' THEN 'Saúde e medicina diagnóstica'
    WHEN 'BBDC3' THEN 'Bancos'
    WHEN 'BBDC4' THEN 'Bancos'
    WHEN 'MOVI3' THEN 'Locação de veículos'
    WHEN 'BRAP4' THEN 'Holding e mineração'
    WHEN 'SBFG3' THEN 'Varejo'
    WHEN 'VAMO3' THEN 'Locação de veículos e máquinas'
    WHEN 'COGN3' THEN 'Educação'
    WHEN 'VBBR3' THEN 'Distribuição de combustíveis'
    WHEN 'ALOS3' THEN 'Shopping centers'
    WHEN 'AXIA6' THEN 'Energia elétrica'
    WHEN 'PRIO3' THEN 'Petróleo, gás e combustíveis'
    WHEN 'AXIA3' THEN 'Energia elétrica'
    WHEN 'ENGI11' THEN 'Energia elétrica'
    WHEN 'VALE3' THEN 'Mineração'
    WHEN 'KLBN11' THEN 'Papel e celulose'
    WHEN 'CPLE3' THEN 'Energia elétrica'
    WHEN 'SMFT3' THEN 'Bem-estar e academias'
    WHEN 'RENT3' THEN 'Locação de veículos'
    WHEN 'BBAS3' THEN 'Bancos'
    WHEN 'TAEE11' THEN 'Energia elétrica'
    WHEN 'CMIG4' THEN 'Energia elétrica'
    WHEN 'CYRE3' THEN 'Construção civil'
    WHEN 'ITSA4' THEN 'Holding financeira'
    WHEN 'JHSF3' THEN 'Imóveis, renda e hotelaria'
    WHEN 'ASAI3' THEN 'Atacarejo e alimentos'
    WHEN 'CURY3' THEN 'Construção civil'
    WHEN 'SLCE3' THEN 'Agropecuária'
    WHEN 'PETR3' THEN 'Petróleo, gás e combustíveis'
    WHEN 'INTB3' THEN 'Tecnologia e equipamentos'
    WHEN 'YDUQ3' THEN 'Educação'
    WHEN 'DIRR3' THEN 'Construção civil'
    WHEN 'MDNE3' THEN 'Construção civil'
    WHEN 'PETR4' THEN 'Petróleo, gás e combustíveis'
    WHEN 'ALPA4' THEN 'Vestuário, calçados e consumo'
    WHEN 'PLPL3' THEN 'Construção civil'
    WHEN 'CMIG3' THEN 'Energia elétrica'
    WHEN 'CMIN3' THEN 'Mineração'
    WHEN 'POMO4' THEN 'Indústria e transporte'
    WHEN 'CPFE3' THEN 'Energia elétrica'
    WHEN 'GGBR4' THEN 'Siderurgia e metalurgia'
    WHEN 'SBSP3' THEN 'Saneamento'
    WHEN 'EMBJ3' THEN 'Aeroespacial e defesa'
    WHEN 'SUZB3' THEN 'Papel e celulose'
    WHEN 'RAIL3' THEN 'Logística e ferrovias'
    WHEN 'MOTV3' THEN 'Concessões e infraestrutura'
    WHEN 'MBRF3' THEN 'Alimentos e proteína animal'
    WHEN 'TIMS3' THEN 'Telecomunicações'
    WHEN 'MGLU3' THEN 'Varejo'
    WHEN 'MULT3' THEN 'Shopping centers'
    WHEN 'TEND3' THEN 'Construção civil'
    WHEN 'GOAU4' THEN 'Holding e siderurgia'
    WHEN 'EGIE3' THEN 'Energia elétrica'
    WHEN 'VIVA3' THEN 'Varejo'
    WHEN 'PSSA3' THEN 'Seguradoras'
    WHEN 'SANB11' THEN 'Bancos'
    WHEN 'PASS3' THEN 'Serviços'
    WHEN 'ITUB3' THEN 'Bancos'
    WHEN 'BEEF3' THEN 'Alimentos e proteína animal'
    WHEN 'BBSE3' THEN 'Seguradoras'
    WHEN 'CEAB3' THEN 'Varejo'
    WHEN 'ITUB4' THEN 'Bancos'
    WHEN 'B3SA3' THEN 'Bolsa e infraestrutura de mercado'
    WHEN 'ECOR3' THEN 'Concessões e infraestrutura'
    WHEN 'ABEV3' THEN 'Bebidas'
    WHEN 'CXSE3' THEN 'Seguradoras'
    WHEN 'ENEV3' THEN 'Energia elétrica'
    WHEN 'ORVR3' THEN 'Saneamento e resíduos'
    WHEN 'BRAV3' THEN 'Petróleo, gás e combustíveis'
    WHEN 'CBAV3' THEN 'Alumínio e mineração'
    WHEN 'EQTL3' THEN 'Energia elétrica'
    WHEN 'BPAC11' THEN 'Bancos e serviços financeiros'
    WHEN 'UGPA3' THEN 'Distribuição de combustíveis'
    WHEN 'GGPS3' THEN 'Serviços corporativos'
    WHEN 'TOTS3' THEN 'Tecnologia'
    WHEN 'CSMG3' THEN 'Saneamento'
    WHEN 'GMAT3' THEN 'Varejo alimentar'
    WHEN 'RDOR3' THEN 'Saúde e hospitais'
    WHEN 'SAUD3' THEN 'Saúde'
    WHEN 'WEGE3' THEN 'Indústria e tecnologia'
    WHEN 'RADL3' THEN 'Farmácias e saúde'
    WHEN 'AURA33' THEN 'Mineração'
    WHEN 'AURE3' THEN 'Energia elétrica'
    WHEN 'CSAN3' THEN 'Energia, açúcar e logística'
    WHEN 'NATU3' THEN 'Consumo e cosméticos'
    WHEN 'HAPV3' THEN 'Saúde e planos de saúde'
    WHEN 'MRVE3' THEN 'Construção civil'
    WHEN 'CSNA3' THEN 'Siderurgia e mineração'
    WHEN 'USIM5' THEN 'Siderurgia e metalurgia'
    WHEN 'BRKM5' THEN 'Química e petroquímica'
    ELSE COALESCE(NULLIF(setor, ''), 'A classificar')
END
WHERE ticker IN (
    'HYPE3','RECV3','ISAE4','SAPR11','IGTI11','ALUP11','SMTO3','VIVT3','LREN3','AZZA3',
    'BRSR6','FLRY3','BBDC3','BBDC4','MOVI3','BRAP4','SBFG3','VAMO3','COGN3','VBBR3',
    'ALOS3','AXIA6','PRIO3','AXIA3','ENGI11','VALE3','KLBN11','CPLE3','SMFT3','RENT3',
    'BBAS3','TAEE11','CMIG4','CYRE3','ITSA4','JHSF3','ASAI3','CURY3','SLCE3','PETR3',
    'INTB3','YDUQ3','DIRR3','MDNE3','PETR4','ALPA4','PLPL3','CMIG3','POMO4','CPFE3',
    'GGBR4','CMIN3','SBSP3','EMBJ3','SUZB3','RAIL3','MOTV3','MBRF3','TIMS3','MGLU3','MULT3',
    'TEND3','GOAU4','EGIE3','VIVA3','PSSA3','SANB11','PASS3','ITUB3','BEEF3','BBSE3',
    'CEAB3','ITUB4','B3SA3','ECOR3','ABEV3','CXSE3','ENEV3','ORVR3','BRAV3','CBAV3',
    'EQTL3','BPAC11','UGPA3','GGPS3','TOTS3','CSMG3','GMAT3','RDOR3','SAUD3','WEGE3',
    'RADL3','AURA33','AURE3','CSAN3','NATU3','HAPV3','MRVE3','CSNA3','USIM5','BRKM5'
);
